#cloud-config
write_files:
  - path: /etc/yandex/unified_agent/config.yml
    content: |
      status:
        enabled: false
        port: "16241"

      storages:
        - name: main
          plugin: fs
          config:
            directory: /var/lib/yandex/unified_agent/main
            max_partition_size: 100mb
            max_segment_size: 10mb

      channels:
        - name: cloud_monitoring
          channel:
            pipe:
              - storage_ref:
                  name: main
            output:
              plugin: yc_metrics
              config:
                folder_id: "${folder_id}"
                iam:
                  cloud_meta: {}

      routes:
        - input:
            plugin: metrics_pull
            config:
              url: http://catgpt:9090
              format:
                prometheus: {}
              namespace: app
          channel:
            channel_ref:
              name: cloud_monitoring

      import:
        - /etc/yandex/unified_agent/conf.d/*.yml
